# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

output: prefixed

tasks:
   default:
      cmds:
         - task: dev:all

   dev:all:
      desc: Run all services
      deps:
         [
            dev:gateway,
            dev:user,
            dev:project,
            dev:mail,
            dev:application,
            dev:ingestion,
            dev:logengine
         ]

   protoc:
      desc: Generate protobuf code
      dir: .
      prefix: 'PROTOC'
      cmds:
         - protoc -I ./shared/proto ./shared/proto/*.proto --go_out=shared --go-grpc_out=shared --go_opt=module=logtheus/shared --go-grpc_opt=module=logtheus/shared

   dev:gateway:
      desc: API Gateway
      dir: ./gateway
      prefix: 'GATEWAY'
      cmds:
         - air -c .air.toml

   dev:user:
      desc: User Service
      dir: ./user-Service
      prefix: 'USER_SERVICE'
      cmds:
         - air -c .air.toml

   dev:project:
      desc: Project Service
      dir: ./project-service
      prefix: 'PROJECT_SERVICE'
      cmds:
         - air -c .air.toml

   dev:mail:
      desc: Mail Service
      dir: ./mail-service
      prefix: 'MAIL_SERVICE'
      cmds:
         - air -c .air.toml

   dev:application:
      desc: Application Service
      dir: ./application-service
      prefix: 'APPLICATION_SERVICE'
      cmds:
         - air -c .air.toml

   dev:ingestion:
      desc: Ingestion Service
      dir: ./ingestion-service
      prefix: 'INGESTION_SERVICE'
      cmds:
         - air -c .air.toml

   dev:logengine:
      desc: Log Engine Service
      dir: ./log-engine-service
      prefix: 'LOG_ENGINE_SERVICE'
      cmds:
         - air -c .air.toml
