package consts

const (
	ERROR_CODE_INTERNAL               = "INTERNAL_ERROR"
	ERROR_CODE_UNKNOWN                = "UNKNOWN_ERROR"
	ERROR_CODE_NOT_FOUND              = "NOT_FOUND"
	ERROR_CODE_USER_EXISTS            = "USER_ALREADY_EXISTS"
	ERROR_CODE_UNAUTHORIZED           = "UNAUTHORIZED"
	ERROR_CODE_FORBIDDEN              = "FORBIDDEN"
	ERROR_CODE_INVALID_CREDENTIALS    = "INVALID_CREDENTIALS"
	ERROR_CODE_EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
	ERROR_CODE_EMAIL_NOT_VERIFIED     = "EMAIL_NOT_VERIFIED"
	ERROR_CODE_INVALID_TOKEN          = "INVALID_TOKEN"
	ERROR_CODE_UNAUTHENTICATED        = "UNAUTHENTICATED"
	ERROR_CODE_VALIDATION_FAILED      = "VALIDATION_FAILED"
	ERROR_CODE_TOO_MANY_PROJECTS      = "TOO_MANY_PROJECTS"
	ERROR_CODE_TOO_MANY_MEMBERS       = "TOO_MANY_MEMBERS"

	INTERNAL_ERROR_CODE_PASSWORD_HASH_FAILED            = "PASSWORD_HASH_FAILED"
	INTERNAL_ERROR_CODE_USER_CREATE_FAILED              = "USER_CREATE_FAILED"
	INTERNAL_ERROR_CODE_VERIFICATION_TOKEN_ISSUE_FAILED = "VERIFICATION_TOKEN_ISSUE_FAILED"
	INTERNAL_ERROR_CODE_USER_VERIFY_EMAIL_FAILED        = "USER_EMAIL_VERIFICATION_FAILED"
	INTERNAL_ERROR_CODE_FAILED_TO_SEND_EMAIL            = "FAILED_TO_SEND_EMAIL"
	INTERNAL_ERROR_CODE_SEND_EMAIL_FAILED               = "SEND_EMAIL_FAILED"
	INTERNAL_ERROR_CODE_TOKEN_GENERATION_FAILED         = "TOKEN_GENERATION_FAILED"
)
