package consts

const (
	ERROR_CODE_INTERNAL               = "INTERNAL_ERROR"
	ERROR_CODE_NOT_FOUND              = "NOT_FOUND"
	ERROR_CODE_USER_EXISTS            = "USER_ALREADY_EXISTS"
	ERROR_CODE_UNAUTHORIZED           = "UNAUTHORIZED"
	ERROR_CODE_FORBIDDEN              = "FORBIDDEN"
	ERROR_CODE_INVALID_CREDENTIALS    = "INVALID_CREDENTIALS"
	ERROR_CODE_EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"

	INTERNAL_ERROR_CODE_PASSWORD_HASH_FAILED            = "PASSWORD_HASH_FAILED"
	INTERNAL_ERROR_CODE_USER_CREATE_FAILED              = "USER_CREATE_FAILED"
	INTERNAL_ERROR_CODE_VERIFICATION_TOKEN_ISSUE_FAILED = "VERIFICATION_TOKEN_ISSUE_FAILED"
	INTERNAL_ERROR_CODE_USER_VERIFY_EMAIL_FAILED        = "USER_EMAIL_VERIFICATION_FAILED"
)
