package consts

var (
	MIN_USERNAME_LEN uint = 4
	MAX_USERNAME_LEN uint = 50

	MIN_PASSWORD_LEN uint = 8

	MIN_PROJECT_NAME_LEN uint = 4
	MAX_PROJECT_NAME_LEN uint = 100

	MIN_PROJECT_DESCRIPTION_LEN uint = 10
	MAX_PROJECT_DESCRIPTION_LEN uint = 500
)
