from enum import Enum


MAX_INGESTION_BYTES = 10 * 1024 * 1024


class LogFormat(str, Enum):
    FORMAT_UNKNOWN = "FORMAT_UNKNOWN"
    FORMAT_JSON = "FORMAT_JSON"
    FORMAT_TEXT = "FORMAT_TEXT"
    FORMAT_BINARY = "FORMAT_BINARY"
