package consts

var (
	MIN_USERNAME_LEN uint = 4
	MAX_USERNAME_LEN uint = 50

	MIN_PASSWORD_LEN uint = 8

	MIN_PROJECT_NAME_LEN uint = 4
	MAX_PROJECT_NAME_LEN uint = 200

	MIN_PROJECT_DESCRIPTION_LEN uint = 5
	MAX_PROJECT_DESCRIPTION_LEN uint = 500

	MIN_APPLICATION_NAME_LEN uint = 4
	MAX_APPLICATION_NAME_LEN uint = 200

	MIN_APPLICATION_DESCRIPTION_LEN uint = 10
	MAX_APPLICATION_DESCRIPTION_LEN uint = 500

	MAX_INGESTION_BYTES = 3 * 1024 * 1024
)
